### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds React 16 compatibility

#### How to test this pull request:
remove old ```node_modules```
run ```npm test```
Use component in main app and ensure usual functionality

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes/82)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package.json, line 48 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQBRBkEx4PhsxGJUA:-L2zQBRBkEx4PhsxGJUB:b-hrcrsc) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/1a32d9fec24189945a20b950346ee2011866593b/package.json#L48)):*
> ```JSON
>     "babel-preset-react": "^6.16.0",
>     "natural": "^0.4.0",
>     "react": "^15.6.1",
> ```

you don't need react?

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQFnNVeeZScPGq9uq:-L2zQFnNVeeZScPGq9ur:ba92d3z) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/d3b5cd07d4a08585514325f22c346a450b9c7e1c/__tests__/AddSomeTests.test.js#L2)):*
> ```JavaScript
> test('We have tests', () => {
>     expect(true).toBeTruthy();
> ```

do we have to make this test pass?

---

*[testSetUp/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQLLkEDucSLlyur8h:-L2zQLLkEDucSLlyur8i:b4cucwp) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/d3b5cd07d4a08585514325f22c346a450b9c7e1c/testSetUp/shim.js#L1)):*
> ```JavaScript
> global.requestAnimationFrame = (callback) => {
> ```

why do we need shim.js?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r2, 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-:-L39Z5Ld_xOVzxVEBhkC:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 3 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQFnNVeeZScPGq9uq:-L3UNSog5fuIhV7vvAmL:bfqml3b) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/d3b5cd07d4a08585514325f22c346a450b9c7e1c/__tests__/AddSomeTests.test.js#L2)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we have to make this test pass?
</blockquote></details>

do we wanna keep this test failing until we write real tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[package.json, line 48 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQBRBkEx4PhsxGJUA:-L3UOZUJSfyEUs4bwPMB:bwdstlp) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/1a32d9fec24189945a20b950346ee2011866593b/package.json#L48)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you don't need react?
</blockquote></details>

We do,  I added it back.

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQFnNVeeZScPGq9uq:-L3UOaiTU4P1LYs0pney:bfq3gdj) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/d3b5cd07d4a08585514325f22c346a450b9c7e1c/__tests__/AddSomeTests.test.js#L2)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we wanna keep this test failing until we write real tests?
</blockquote></details>

Not sure.

---

*[testSetUp/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQLLkEDucSLlyur8h:-L3UObhsm8T1iVcF0NcR:b-7i6e14) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/d3b5cd07d4a08585514325f22c346a450b9c7e1c/testSetUp/shim.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do we need shim.js?
</blockquote></details>

to make react work with  material-ui

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-L2zQFnNVeeZScPGq9uq:-L3UOyGRZwC354biMmA9:b-d6nivm) ([raw file](https://github.com/translationcoreapps/translationnotes/blob/d3b5cd07d4a08585514325f22c346a450b9c7e1c/__tests__/AddSomeTests.test.js#L2)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Not sure.
</blockquote></details>

we may want to make it fail until we write real tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes/82#-:-L3Y5JIZAAa4AJRROsmX:bnfp4nl)*

**Pull request merged**
